---
name: Weekly monitoring for platform operations teams
trigger: none
pr:
  - master
schedules:
  - cron: "45 7 * * Mon-Fri"
    displayName: Runs 9 AM Mon-Fri
    branches:
      include:
        - master
    always: "true"

parameters:
  - name: gh_workflows
    type: object
    default:
      - repo: "cnp-java-base"
        branch: "master"
        run: "cd"
      - repo: "cnp-node-base"
        branch: "master"
        run: "cd"
      - repo: "tech-docs-monitor"
        branch: "main"
        run: ".github/workflows/run.yml"
      - repo: "auto-shutdown"
        branch: "master"
        run: "aks-auto-start"
      - repo: "auto-shutdown"
        branch: "master"
        run: "aks-auto-shutdown"
      - repo: "auto-shutdown"
        branch: "master"
        run: "VM-auto-start"
      - repo: "auto-shutdown"
        branch: "master"
        run: "vm-auto-shutdown"
      - repo: "auto-shutdown"
        branch: "master"
        run: "AppGateway-auto-start"
      - repo: "auto-shutdown"
        branch: "master"
        run: "AppGateway-auto-shutdown"
      - repo: "auto-shutdown"
        branch: "master"
        run: "flexible-server-auto-start"
      - repo: "auto-shutdown"
        branch: "master"
        run: "flexible-server-auto-shutdown"
  - name: ado_pipelines
    type: object
    default:
      - project: "PlatformOperations"
        definitionId: "802"
        timeForAmber: "3"
        timeForRed: "5"
        pipelineName: Preview_Helm_release_cleanup_-_scheduled
        branchName: refs/heads/master
      - project: "PlatformOperations"
        definitionId: "840"
        timeForAmber: "3"
        timeForRed: "5"
        pipelineName: Preview_Helm_release_cleanup_-_PR_close
        branchName: refs/heads/master
      - project: "PlatformOperations"
        definitionId: "768"
        timeForAmber: "3"
        timeForRed: "7"
        pipelineName: ACR_Cleanup
        branchName: refs/heads/master
      - project: "PlatformOperations"
        definitionId: "777"
        timeForAmber: "14"
        timeForRed: "28"
        pipelineName: Launch_Darkly_cleanup
        branchName: refs/heads/master
      - project: "PlatformOperations"
        definitionId: "472"
        timeForAmber: "3"
        timeForRed: "7"
        pipelineName: Azure_AAD_group_cleanup
        branchName: refs/heads/master
      - project: "PlatformOperations"
        definitionId: "771"
        timeForAmber: "3"
        timeForRed: "7"
        pipelineName: OWASP_DB_Update_-_Production
        branchName: refs/heads/master
      - project: "PlatformOperations"
        definitionId: "808"
        timeForAmber: "3"
        timeForRed: "7"
        pipelineName: OWASP_DB_Update_-_Sandbox
        branchName: refs/heads/master
      - project: "PlatformOperations"
        definitionId: "772"
        timeForAmber: "3"
        timeForRed: "7"
        pipelineName: ACR_Base_importer
        branchName: refs/heads/master
      - project: "PlatformOperations"
        definitionId: "635"
        timeForAmber: "1"
        timeForRed: "3"
        pipelineName: "hmcts.azure-enterprise"
        branchName: refs/heads/main
      - project: "PlatformOperations"
        definitionId: "543"
        timeForAmber: "1"
        timeForRed: "3"
        pipelineName: sds-azure-platform
        branchName: refs/heads/master
      - project: "PlatformOperations"
        definitionId: "765"
        timeForAmber: "1"
        timeForRed: "3"
        pipelineName: azure-platform-terraform
        branchName: refs/heads/master
      - project: "PlatformOperations"
        definitionId: "821"
        timeForAmber: "5"
        timeForRed: "7"
        pipelineName: azure-app-proxy
        branchName: refs/heads/main
  - name: aks_clusters
    type: object
    default:
      - resourceGroup: "cft-preview-00-rg"
        clusterName: "cft-preview-00-aks"
        subscription: "DCD-CFTAPPS-DEV"
      - resourceGroup: "cft-preview-01-rg"
        clusterName: "cft-preview-01-aks"
        subscription: "DCD-CFTAPPS-DEV"
  - name: recovery_services_vaults
    type: object
    default:
      - resourceGroup: "bau-bais_prod_resource_group"
        vaultName: "recovery-vault-dmz-bau-bais-prod"
        subscription: "DTS-SHAREDSERVICES-PROD"
      - resourceGroup: "bau-bais_prod_resource_group"
        vaultName: "recovery-vault-eft-bau-bais-prod"
        subscription: "DTS-SHAREDSERVICES-PROD"
      - resourceGroup: "libragob-prod-rg"
        vaultName: "LIBRAGOB-DB-MIGRATION-PROD-RSV-01"
        subscription: "DTS-SHAREDSERVICES-PROD"
      - resourceGroup: "externalspoke-rg"
        vaultName: "RSV-PROD-UKS-HER-01"
        subscription: "DTS-HERITAGE-EXTSVC-PROD"
      - resourceGroup: "internalspoke-rg"
        vaultName: "RSV-PROD-UKS-HER-02"
        subscription: "DTS-HERITAGE-INTSVC-PROD"
  - name: certificates
    type: object
    default:
      - subscription: "DCD-CFTAPPS-PROD"
        resource_group: "lz-prod-rg"
        front_door_name: "hmcts-prod"
        min_cert_exp_days: "14"
      - subscription: "DTS-SHAREDSERVICES-PROD"
        resource_group: "lz-prod-rg"
        front_door_name: "sdshmcts-prod"
        min_cert_exp_days: "14"
      - subscription: "DCD-CFTAPPS-SBOX"
        resource_group: "lz-sbox-rg"
        front_door_name: "hmcts-sbox"
        min_cert_exp_days: "14"
      - subscription: "DTS-SHAREDSERVICES-PROD"
        resource_group: "bau-bais_prod_network_rg"
        front_door_name: "hmcts-heritage-prod"
        min_cert_exp_days: "14"

variables:
  - name: SPSecretNumDays
    value: 14
  - name: service_connection
    value: dts-management-prod-intsvc
  - name: ado_service_connection
    value: OPS-APPROVAL-GATE-MGMT-ENVS
  - name: isMain
    value: $[in(variables['Build.SourceBranch'], 'refs/heads/main', 'refs/heads/master')]
  - name: isAutoTriggered
    value: $[in(variables['Build.Reason'], 'BatchedCI', 'IndividualCI', 'PullRequest', 'Schedule')] # does not include manually running pipeline from UI (i.e. manual trigger).
  - name: jenkins_url
    value: "http://jenkins.jenkins:8080/"
  - name: main_channel
    value: jh-test-1
  - name: pull_request_number
    value: $(system.pullRequest.pullRequestNumber)

jobs:
  - job: DailyMonitoring
    timeoutInMinutes: 20
    pool:
      name: "hmcts-cftptl-agent-pool"
    steps:
      - task: AzureKeyVault@1
        displayName: "Get secrets from Keyvault"
        inputs:
          azureSubscription: "DTS-CFTPTL-INTSVC"
          keyVaultName: "cftptl-intsvc"
          secretsFilter: "dtspo-weekly-pr-bot-url,azure-devops-token,jira-password,jira-username,github-management-api-token,jenkins-api-user,jenkins-api-token,service-now-username,service-now-password,launchdarkly-access-token"
      - task: Bash@3
        displayName: "Create a slack message file"
        inputs:
          targetType: "inline"
          script: |
            echo "*Weekly PR's by User* \n \n">> slack-message.txt
      - task: Bash@3
        displayName: "Checking Github Licenses"
        inputs:
          targetType: filePath
          filePath: scripts/get-prs-by-user.sh
          arguments: $(github-management-api-token)
      - task: Bash@3
        displayName: "Github workflow status header"
        inputs:
          targetType: "inline"
          script: |
            echo "\n:github: *GitHub Scheduled Workflow Status* \n\n" >> slack-message.txt
      - ${{ each gh_workflow in parameters.gh_workflows }}:
          - task: Bash@3
            displayName: "Check Github workflow Runs"
            inputs:
              targetType: filePath
              filePath: scripts/github-scheduled-workflow-monitor.sh
              arguments: $(github-management-api-token) ${{gh_workflow.repo}} ${{gh_workflow.branch}} ${{gh_workflow.run}}
      - task: Bash@3
        displayName: "Send slack message - master branch"
        condition: |
          and(succeeded(), eq(variables['isMain'], true))
        inputs:
          targetType: filePath
          filePath: scripts/send-slack-message.sh
          arguments: $(dtspo-weekly-pr-bot-url) ${{ variables.main_channel }}
