name: Weekly PR check
on:
  workflow_dispatch:
  schedule:
    - cron: '0 8 * * 1' # Every Monday at 08:00
env:
  GH_TOKEN: ${{ secrets.PLATFORM_USER_TOKEN }}
permissions:
  id-token: write
jobs:
  weekly:
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
      #Uncomment for troubleshooting   
      #- name: Dump context
        #uses: crazy-max/ghaction-dump-context@v2
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: '0'
          token: ${{ env.GH_TOKEN }}
          
      - name: Get PR's by assignee
        run: ./scripts/get-prs-by-user.sh
        env:
          GITHUB_TOKEN: ${{ env.GH_TOKEN }}
          